# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeFMfz4skxu9umXarZcS8HnOQmdSmwAc

## **Linear Regression Practical**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/height-weight.csv')

df

plt.scatter(x=df['Weight'],y=df['Height'])
plt.xlabel('Weight')
plt.ylabel('Height')

sns.heatmap(data=df.corr(),annot=True)

df.corr()

X=df[['Weight']]
y=df['Height']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
lr=LinearRegression(n_jobs=-1)
lr.fit(X_train,y_train)

lr.predict(X_test)

#This regression model has both coefficient(slope) and intercept
print("Slope of the best fit line:",lr.coef_)
print("Intercept of the best fit line:",lr.intercept_)

lr.predict(scaler.transform([[64]]))

plt.scatter(X_train,y_train)
plt.plot(X_train,lr.predict(X_train))

import statsmodels.api as sm
model=sm.OLS(y_train,X_train).fit()  #here we have to give first dependent variable then independent variable

y_pred=model.predict(X_test)
y_pred

print(model.summary())

